name: Ub
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
                  
      - name: Set up JDK
        run: sudo apt-get install openjdk-7-jdk

      - name: Set up android SDK
        run: | 
             wget http://dl.google.com/android/android-sdk_r24.2-linux.tgz
             tar -xvf android-sdk_r24.2-linux.tgz
             cd android-sdk-linux/tools

  
