name: Ub
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
                  
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Set up android SDK
        run: sudo apt update && sudo apt install android-sdk    

      - name: Set up android SDK
        run: ${ANDROID_HOME}/tools/bin/sdkmanager --install "system-images;android-29;google_apis_playstore;x86_64"


      - name: Accept licenses
        run: echo y | sdkmanager --licenses
