name: Ub
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
                  
      - name: Set up JDK
        if: steps.cache-jdk.outputs.cache-hit != 'true'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'


      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
