
name: Ub
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
                  
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '29'
        ndk-version: '21.4.7075529'


    - name: Start Android Emulator (ARM)
      run: emulator -avd testAVD -no-window -no-audio -qemu -cpu cortex-a53

    - name: Stop Android Emulator
      run: adb emu kill
