
name: Caching
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v3
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '8'

          - name: Setup Android SDK
            uses: android-actions/setup-android@v2
  
          - name: accept licenses
            run: yes | sdkmanager --licenses > /dev/null
