
name: Caching
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'


      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
  
      - name: accept licenses
        run: yes | sdkmanager --licenses  
