name: Ub
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
                  
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Set up android SDK
        run: sudo apt update && sudo apt install android-sdk    


      - name: Accept licenses
        run: echo y | sdkmanager --licenses


      
      - name: Start Emulator
        run: |
          export ANDROID_SDK_ROOT=$RUNNER_WORKSPACE/Android/sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools/bin
          emulator -avd oui -no-window -gpu swiftshader_indirect -no-audio -no-snapshot-save -no-snapshot-load &
          android-wait-for-emulator
