
name: Ub
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
                  
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '29'
        ndk-version: '21.4.7075529'

    - name: Start Android Emulator
      run: |
        $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD -no-window -no-audio &
        sleep 30  # Adjust the sleep duration based on your emulator startup time
        adb wait-for-device
        adb shell input keyevent 82
